spring:
  nodeValue: ''
  datasource:
    username: system
    dbcp2:
      max-conn-lifetime-millis: '100000'
      intial-size: '10'
      max-total: '100'
    url: jdbc:oracle:thin:@localhost:1521:xe
    type: orcle.ucp.jdbc.PoolDataSourceImpl
    password: santosh
datasource: ''
driver-class-name: orcale.jdbc.driver.OracleDriver
 