#Activate the profile
spring: 
 profiles: 
   active: test

---
   
spring:
 config: 
   activate: 
    on-profile: dev
    
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql:///NTSBMS616DB
  username: root
  password: root
  dbcp2.max-total: 100
  dbcp2.intial-size: 10
  dbcp2.max-conn-lifetime-millis: 100000
  type: org.apache.commons.dbcp2.BasicDataSource
  
---
  
spring:
 config: 
   activate: 
    on-profile: test
    
    
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql:///NTSBMS616DB
  type: com.mchange.v2.c3p0.ComboPooledDataSource
  username: root
  password: root
  c3po: 
  maxSize: 100
  minSize: 10
  
  
---
  
spring:
 config: 
   activate: 
    on-profile: uat
         
datasource:
   driver-class-name: orcle.jdbc.driver.orcleDriver
   username: system
   url: jdbc:oracle:thin:@localhost:1521:xe
   oracleucp: 
     max-pool-size: 100
     time-to-live-connection-timeout: 10000
     min-pool-size: 10
   type: oracle.ucp.jdbc.PoolDataSourceImpl
   password: santosh
 
  
---
  
spring:
 config: 
   activate: 
    on-profile: prod
    
datasource: 
   driver-class-name: orcle.jdbc.driver.orcleDriver
   hikari: 
    keepalive-time: 100000
    maximum-pool-size: 100
    minimum-idle: 10
    username: system
   url: jdbc:oracle:thin:@localhost:1521:xe
   password: santosh
 
       